### ISSUE TITLE
Failure to build windows project due to missing dependency 'atlstr.h'.

### ISSUE THREAD

**Issue by coman3** [invertase/flutter_desktop_webview_auth#22]
HI there,

I'm not super versed in the world of C++ windows builds, however I am running over a weird issue when building using this package on my brand new flutter application. :

<details>
  <summary>The full log of a windows build</summary>

  ```
  PS> flutter build windows --verbose
  [  +58 ms] executing: [C:\tools\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
  [ +212 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
  [   +1 ms] ee4e09cce01d6f2d7f4baebd247fde02e5008851
  [        ] executing: [C:\tools\flutter/] git tag --points-at ee4e09cce01d6f2d7f4baebd247fde02e5008851
  [  +46 ms] Exit code 0 from: git tag --points-at ee4e09cce01d6f2d7f4baebd247fde02e5008851
  [        ] 3.0.0
  [   +7 ms] executing: [C:\tools\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
  [  +35 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
  [        ] origin/stable
  [        ] executing: [C:\tools\flutter/] git ls-remote --get-url origin
  [  +31 ms] Exit code 0 from: git ls-remote --get-url origin
  [        ] https://github.com/flutter/flutter.git
  [  +97 ms] executing: [C:\tools\flutter/] git rev-parse --abbrev-ref HEAD
  [  +32 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
  [        ] stable
  [  +64 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
  [   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
  [  +47 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
  [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
  [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
  [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
  [   +2 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
  [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
  [  +42 ms] Skipping pub get: version match.
  [  +27 ms] Found plugin desktop_webview_auth at C:\tools\flutter\.pub-cache\hosted\pub.dartlang.org\desktop_webview_auth-0.0.9\
  [   +7 ms] Found plugin firebase_auth at C:\tools\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-3.3.18\
  [   +3 ms] Found plugin firebase_auth_desktop at C:\tools\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_desktop-1.0.0\
  [   +2 ms] Found plugin firebase_auth_web at C:\tools\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-3.3.15\
  [   +2 ms] Found plugin firebase_core at C:\tools\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.17.0\
  [   +1 ms] Found plugin firebase_core_desktop at C:\tools\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_desktop-1.0.0\
  [   +1 ms] Found plugin firebase_core_web at C:\tools\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-1.6.4\
  [  +51 ms] Found plugin desktop_webview_auth at C:\tools\flutter\.pub-cache\hosted\pub.dartlang.org\desktop_webview_auth-0.0.9\
  [   +2 ms] Found plugin firebase_auth at C:\tools\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-3.3.18\
  [   +2 ms] Found plugin firebase_auth_desktop at C:\tools\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_desktop-1.0.0\
  [   +1 ms] Found plugin firebase_auth_web at C:\tools\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-3.3.15\
  [   +1 ms] Found plugin firebase_core at C:\tools\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.17.0\
  [   +1 ms] Found plugin firebase_core_desktop at C:\tools\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_desktop-1.0.0\
  [   +1 ms] Found plugin firebase_core_web at C:\tools\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-1.6.4\
  [  +54 ms] Generating D:\Source\myuiproject\ui\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
  [  +63 ms]  Building with sound null safety 
  [  +13 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires
  Microsoft.VisualStudio.Workload.NativeDesktop Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
  [  +32 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires
  Microsoft.VisualStudio.Workload.NativeDesktop Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
  [        ] []
  [        ] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires
  Microsoft.VisualStudio.Workload.VCTools Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
  [  +31 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires
  Microsoft.VisualStudio.Workload.VCTools Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
  [        ] [
               {
                 "instanceId": "55051bc2",
                 "installDate": "2022-03-25T07:19:45Z",
                 "installationName": "VisualStudio/16.11.14+32428.217",
                 "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools",
                 "installationVersion": "16.11.32428.217",
                 "productId": "Microsoft.VisualStudio.Product.BuildTools",
                 "productPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\Common7\\Tools\\LaunchDevCmd.bat",
                 "state": 4294967295,
                 "isComplete": true,
                 "isLaunchable": true,
                 "isPrerelease": false,
                 "isRebootRequired": false,
                 "displayName": "Visual Studio Build Tools 2019",
                 "description": "The Visual Studio Build Tools allows you to build native and managed MSBuild-based applications without requiring the Visual Studio IDE. There are     
                 options to install the Visual C++ compilers and libraries, MFC, ATL, and C++/CLI support.",
                 "channelId": "VisualStudio.16.Release",
                 "channelUri": "https://aka.ms/vs/16/release/channel",
                 "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
                 "installedChannelUri": "https://aka.ms/vs/16/release/channel",
                 "releaseNotes": "https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-v16.11#16.11.14",
                 "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660909",
                 "updateDate": "2022-05-17T02:35:49.8541373Z",
                 "catalog": {
                   "buildBranch": "d16.11",
                   "buildVersion": "16.11.32428.217",
                   "id": "VisualStudio/16.11.14+32428.217",
                   "localBuild": "build-lab",
                   "manifestName": "VisualStudio",
                   "manifestType": "installer",
                   "productDisplayVersion": "16.11.14",
                   "productLine": "Dev16",
                   "productLineVersion": "2019",
                   "productMilestone": "RTW",
                   "productMilestoneIsPreRelease": "False",
                   "productName": "Visual Studio",
                   "productPatchVersion": "14",
                   "productPreReleaseMilestoneSuffix": "1.0",
                   "productSemanticVersion": "16.11.14+32428.217",
                   "requiredEngineVersion": "2.11.69.53063"
                 },
                 "properties": {
                   "campaignId": "2030",
                   "channelManifestId": "VisualStudio.16.Release/16.11.14+32428.217",
                   "nickname": "",
                   "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\setup.exe"
                 }
               }
             ]
  [   +5 ms] Building Windows application...
  [  +14 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe -S
  D:\Source\myuiproject\ui\windows -B build\windows -G Visual Studio 16 2019
  [  +58 ms] -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22000.
  [  +48 ms] Nuget is not installed.
  [  +47 ms] -- Configuring done
  [ +135 ms] -- Generating done
  [  +14 ms] -- Build files have been written to: D:/Source/myuiproject/ui/build/windows
  [   +7 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe --build build\windows --config
  Release --target INSTALL --verbose
  [ +107 ms] Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
  [        ] Copyright (C) Microsoft Corporation. All rights reserved.
  [  +40 ms] Build started 17/05/2022 12:54:55 PM.
  [ +183 ms] Project "D:\Source\myuiproject\ui\build\windows\INSTALL.vcxproj" on node 1 (default targets).
  [        ] Project "D:\Source\myuiproject\ui\build\windows\INSTALL.vcxproj" (1) is building "D:\Source\myuiproject\ui\build\windows\ZERO_CHECK.vcxproj" (2) on
  node 1 (default targets).
  [        ] InitializeBuildStatus:
  [        ]   Creating "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
  [  +20 ms] CustomBuild:
  [        ]   All outputs are up-to-date.
  [  +22 ms] FinalizeBuildStatus:
  [        ]   Deleting file "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
  [        ]   Touching "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
  [        ] Done Building Project "D:\Source\myuiproject\ui\build\windows\ZERO_CHECK.vcxproj" (default targets).
  [  +40 ms] Project "D:\Source\myuiproject\ui\build\windows\INSTALL.vcxproj" (1) is building "D:\Source\myuiproject\ui\build\windows\ALL_BUILD.vcxproj" (3) on
  node 1 (default targets).
  [        ] Project "D:\Source\myuiproject\ui\build\windows\ALL_BUILD.vcxproj" (3) is building
  "D:\Source\myuiproject\ui\build\windows\plugins\desktop_webview_auth\desktop_webview_auth_DEPENDENCIES_DOWNLOAD.vcxproj" (4) on node 1 (default targets).
  [        ] InitializeBuildStatus:
  [        ]   Creating "x64\Release\desktop_webview_auth_DEPENDENCIES_DOWNLOAD\desktop_.8BAC91A2.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
  [   +4 ms] PreBuildEvent:
  [        ]   setlocal
  [        ]   ..\..\nuget.exe install Microsoft.Windows.ImplementationLibrary -Version 1.0.211019.2 -ExcludeVersion -OutputDirectory
  D:/Source/myuiproject/ui/build/windows/packages
  [        ]   if %errorlevel% neq 0 goto :cmEnd
  [        ]   ..\..\nuget.exe install Microsoft.Web.WebView2 -Version 1.0.1108.44 -ExcludeVersion -OutputDirectory D:/Source/myuiproject/ui/build/windows/packages
  [        ]   if %errorlevel% neq 0 goto :cmEnd
  [        ]   :cmEnd
  [        ]   endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
  [        ]   :cmErrorLevel
  [        ]   exit /b %1
  [        ]   :cmDone
  [        ]   if %errorlevel% neq 0 goto :VCEnd
  [        ]   :VCEnd
  [ +466 ms]   Feeds used:
  [        ]     C:\Users\LachlanvanderVelden\.nuget\packages\
  [        ]     https://api.nuget.org/v3/index.json
  [        ]     C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
  [  +53 ms]   Package "Microsoft.Windows.ImplementationLibrary.1.0.211019.2" is already installed.
  [ +457 ms]   Feeds used:
  [        ]     C:\Users\LachlanvanderVelden\.nuget\packages\
  [        ]     https://api.nuget.org/v3/index.json
  [        ]     C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
  [  +56 ms]   Package "Microsoft.Web.WebView2.1.0.1108.44" is already installed.
  [  +13 ms] CustomBuild:
  [        ]   All outputs are up-to-date.
  [   +4 ms] FinalizeBuildStatus:
  [        ]   Deleting file "x64\Release\desktop_webview_auth_DEPENDENCIES_DOWNLOAD\desktop_.8BAC91A2.tlog\unsuccessfulbuild".
  [        ]   Touching "x64\Release\desktop_webview_auth_DEPENDENCIES_DOWNLOAD\desktop_.8BAC91A2.tlog\desktop_webview_auth_DEPENDENCIES_DOWNLOAD.lastbuildstate".
  [        ] Done Building Project "D:\Source\myuiproject\ui\build\windows\plugins\desktop_webview_auth\desktop_webview_auth_DEPENDENCIES_DOWNLOAD.vcxproj" (default        
  targets).
  [  +66 ms] Project "D:\Source\myuiproject\ui\build\windows\ALL_BUILD.vcxproj" (3) is building
  "D:\Source\myuiproject\ui\build\windows\plugins\desktop_webview_auth\desktop_webview_auth_plugin.vcxproj" (5) on node 1 (default targets).
  [        ] Project "D:\Source\myuiproject\ui\build\windows\plugins\desktop_webview_auth\desktop_webview_auth_plugin.vcxproj" (5) is building
  "D:\Source\myuiproject\ui\build\windows\flutter\flutter_assemble.vcxproj" (6) on node 1 (default targets).
  [        ] InitializeBuildStatus:
  [        ]   Creating "x64\Release\flutter_assemble\flutter_assemble.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
  [   +4 ms] CustomBuild:
  [        ]   "The build of 'D:\Source\myuiproject\ui\build\windows\CMakeFiles\88677038c5d6a27bae034ffd5aa564c4\flutter_assemble.rule' depends on
  'D:\SOURCE\myuiproject\UI\WINDOWS\FLUTTER\EPHEMERAL\FLUTTER_WINDOWS.DLL' which is produced by the build of
  'D:\Source\myuiproject\ui\build\windows\CMakeFiles\84ed994327e2464e5e583f47d0892c9f\flutter_windows.dll.rule'. The items cannot be built in parallel."
  [  +41 ms]   Generating D:/Source/myuiproject/ui/windows/flutter/ephemeral/flutter_windows.dll,
  D:/Source/myuiproject/ui/windows/flutter/ephemeral/flutter_export.h, D:/Source/myuiproject/ui/windows/flutter/ephemeral/flutter_windows.h,
  D:/Source/myuiproject/ui/windows/flutter/ephemeral/flutter_messenger.h, D:/Source/myuiproject/ui/windows/flutter/ephemeral/flutter_plugin_registrar.h,        
  D:/Source/myuiproject/ui/windows/flutter/ephemeral/flutter_texture_registrar.h,
  D:/Source/myuiproject/ui/windows/flutter/ephemeral/cpp_client_wrapper/core_implementations.cc,
  D:/Source/myuiproject/ui/windows/flutter/ephemeral/cpp_client_wrapper/standard_codec.cc,
  D:/Source/myuiproject/ui/windows/flutter/ephemeral/cpp_client_wrapper/plugin_registrar.cc,
  D:/Source/myuiproject/ui/windows/flutter/ephemeral/cpp_client_wrapper/flutter_engine.cc,
  D:/Source/myuiproject/ui/windows/flutter/ephemeral/cpp_client_wrapper/flutter_view_controller.cc, _phony_
  [ +854 ms]   [  +56 ms] executing: [C:\tools\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
  [ +200 ms]   [ +218 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
  [        ]   [        ] ee4e09cce01d6f2d7f4baebd247fde02e5008851
  [        ]   [        ] executing: [C:\tools\flutter/] git tag --points-at ee4e09cce01d6f2d7f4baebd247fde02e5008851
  [  +52 ms]   [  +52 ms] Exit code 0 from: git tag --points-at ee4e09cce01d6f2d7f4baebd247fde02e5008851
  [        ]   [        ] 3.0.0
  [   +6 ms]   [   +6 ms] executing: [C:\tools\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
  [  +37 ms]   [  +37 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
  [        ]   [        ] origin/stable
  [        ]   [        ] executing: [C:\tools\flutter/] git ls-remote --get-url origin
  [  +38 ms]   [  +38 ms] Exit code 0 from: git ls-remote --get-url origin
  [        ]   [        ] https://github.com/flutter/flutter.git
  [  +45 ms]   [  +46 ms] executing: [C:\tools\flutter/] git rev-parse --abbrev-ref HEAD
  [  +39 ms]   [  +39 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
  [        ]   [        ] stable
  [  +58 ms]   [  +58 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
  [        ]   [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
  [        ]   [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
  [        ]   [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
  [   +1 ms]   [   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
  [        ]   [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
  [        ]   [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
  [        ]   [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
  [        ]   [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
  [        ]   [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
  [        ]   [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
  [        ]   [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
  [  +79 ms]   [  +80 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
  [        ]   [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
  [        ]   [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
  [        ]   [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
  [        ]   [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
  [        ]   [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
  [        ]   [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
  [        ]   [   +1 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
  [        ]   [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
  [        ]   [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
  [        ]   [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
  [        ]   [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
  [        ]   [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
  [        ]   [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
  [        ]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
  [        ]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
  [        ]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
  [        ]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
  [        ]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
  [        ]   [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
  [        ]   [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
  [  +25 ms]   [  +28 ms] Initializing file store
  [  +14 ms]   [  +14 ms] Done initializing file store
  [  +52 ms]   [  +52 ms] Skipping target: gen_localizations
  [  +11 ms]   [  +11 ms] Skipping target: gen_dart_plugin_registrant
  [+1662 ms]   [+1662 ms] Skipping target: unpack_windows
  [ +355 ms]   [ +355 ms] Skipping target: kernel_snapshot
  [  +18 ms]   [  +18 ms] Skipping target: aot_elf_release
  [  +16 ms]   [  +16 ms] Skipping target: windows_aot_bundle
  [  +32 ms]   [  +32 ms] Skipping target: release_bundle_windows_assets
  [        ]   [        ] Persisting file store
  [   +9 ms]   [   +9 ms] Done persisting file store
  [   +4 ms]   [   +4 ms] build succeeded.
  [   +7 ms]   [   +7 ms] "flutter assemble" took 2,314ms.
  [ +256 ms]   [ +255 ms] ensureAnalyticsSent: 252ms
  [        ]   [        ] Running shutdown hooks
  [        ]   [        ] Shutdown hooks complete
  [        ]   [        ] exiting with code 0
  [  +53 ms] FinalizeBuildStatus:
  [        ]   Deleting file "x64\Release\flutter_assemble\flutter_assemble.tlog\unsuccessfulbuild".
  [        ]   Touching "x64\Release\flutter_assemble\flutter_assemble.tlog\flutter_assemble.lastbuildstate".
  [        ] Done Building Project "D:\Source\myuiproject\ui\build\windows\flutter\flutter_assemble.vcxproj" (default targets).
  [  +26 ms] Project "D:\Source\myuiproject\ui\build\windows\plugins\desktop_webview_auth\desktop_webview_auth_plugin.vcxproj" (5) is building
  "D:\Source\myuiproject\ui\build\windows\flutter\flutter_wrapper_plugin.vcxproj" (7) on node 1 (default targets).
  [        ] InitializeBuildStatus:
  [        ]   Creating "flutter_wrapper_plugin.dir\Release\flutter_.1808AA4A.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
  [        ] CustomBuild:
  [        ]   All outputs are up-to-date.
  [  +30 ms] ClCompile:
  [        ]   All outputs are up-to-date.
  [  +17 ms] Lib:
  [        ]   All outputs are up-to-date.
  [        ]   flutter_wrapper_plugin.vcxproj -> D:\Source\myuiproject\ui\build\windows\flutter\Release\flutter_wrapper_plugin.lib
  [   +7 ms] FinalizeBuildStatus:
  [        ]   Deleting file "flutter_wrapper_plugin.dir\Release\flutter_.1808AA4A.tlog\unsuccessfulbuild".
  [        ]   Touching "flutter_wrapper_plugin.dir\Release\flutter_.1808AA4A.tlog\flutter_wrapper_plugin.lastbuildstate".
  [        ] Done Building Project "D:\Source\myuiproject\ui\build\windows\flutter\flutter_wrapper_plugin.vcxproj" (default targets).
  [   +5 ms] InitializeBuildStatus:
  [        ]   Touching "desktop_webview_auth_plugin.dir\Release\desktop_.75CC8517.tlog\unsuccessfulbuild".
  [   +1 ms] CustomBuild:
  [        ]   All outputs are up-to-date.
  [   +9 ms] ClCompile:
  [        ]   C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\CL.exe /c
  /ID:\Source\myuiproject\ui\build\windows\packages\Microsoft.Windows.ImplementationLibrary\build\native\..\..\include\
  /ID:\Source\myuiproject\ui\build\windows\packages\Microsoft.Web.WebView2\build\native\include\ /ID:\Source\myuiproject\ui\windows\flutter\ephemeral
  /ID:\Source\myuiproject\ui\windows\flutter\ephemeral\cpp_client_wrapper\include /nologo /W4 /WX /diagnostics:column /O2 /Ob2 /D WIN32 /D _WINDOWS /D NDEBUG /D
  _HAS_EXCEPTIONS=0 /D FLUTTER_PLUGIN_IMPL /D UNICODE /D _UNICODE /D "CMAKE_INTDIR=\"Release\"" /D desktop_webview_auth_plugin_EXPORTS /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MD 
  /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /std:c++17 /Fo"desktop_webview_auth_plugin.dir\Release\\" /Fd"desktop_webview_auth_plugin.dir\Release\vc142.pdb" /external:W4 
  /Gd /TP /wd4100 /errorReport:queue D:\Source\myuiproject\ui\windows\flutter\ephemeral\.plugin_symlinks\desktop_webview_auth\windows\desktop_webview_auth_plugin.cpp       
  [  +45 ms]   desktop_webview_auth_plugin.cpp
  [ +785 ms] D:\Source\myuiproject\ui\windows\flutter\ephemeral\.plugin_symlinks\desktop_webview_auth\windows\desktop_webview_auth_plugin.cpp(20,10): fatal error C1083:
  Cannot open include file: 'atlstr.h': No such file or directory [D:\Source\myuiproject\ui\build\windows\plugins\desktop_webview_auth\desktop_webview_auth_plugin.vcxproj] 
  [ +143 ms] Done Building Project "D:\Source\myuiproject\ui\build\windows\plugins\desktop_webview_auth\desktop_webview_auth_plugin.vcxproj" (default targets) -- FAILED.
  [  +30 ms] Project "D:\Source\myuiproject\ui\build\windows\ALL_BUILD.vcxproj" (3) is building
  "D:\Source\myuiproject\ui\build\windows\flutter\flutter_wrapper_app.vcxproj" (8) on node 1 (default targets).
  [        ] InitializeBuildStatus:
  [        ]   Creating "flutter_wrapper_app.dir\Release\flutter_.7F11BBD8.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
  [        ] CustomBuild:
  [        ]   All outputs are up-to-date.
  [   +6 ms] ClCompile:
  [        ]   All outputs are up-to-date.
  [   +2 ms] Lib:
  [        ]   All outputs are up-to-date.
  [        ]   flutter_wrapper_app.vcxproj -> D:\Source\myuiproject\ui\build\windows\flutter\Release\flutter_wrapper_app.lib
  [   +3 ms] FinalizeBuildStatus:
  [        ]   Deleting file "flutter_wrapper_app.dir\Release\flutter_.7F11BBD8.tlog\unsuccessfulbuild".
  [        ]   Touching "flutter_wrapper_app.dir\Release\flutter_.7F11BBD8.tlog\flutter_wrapper_app.lastbuildstate".
  [        ] Done Building Project "D:\Source\myuiproject\ui\build\windows\flutter\flutter_wrapper_app.vcxproj" (default targets).
  [  +28 ms] Done Building Project "D:\Source\myuiproject\ui\build\windows\ALL_BUILD.vcxproj" (default targets) -- FAILED.
  [        ] Done Building Project "D:\Source\myuiproject\ui\build\windows\INSTALL.vcxproj" (default targets) -- FAILED.
  [        ] Build FAILED.
  [   +2 ms] "D:\Source\myuiproject\ui\build\windows\INSTALL.vcxproj" (default target) (1) ->
  [        ] "D:\Source\myuiproject\ui\build\windows\ALL_BUILD.vcxproj" (default target) (3) ->
  [        ] "D:\Source\myuiproject\ui\build\windows\plugins\desktop_webview_auth\desktop_webview_auth_plugin.vcxproj" (default target) (5) ->
  [        ] (ClCompile target) ->
  [        ]   D:\Source\myuiproject\ui\windows\flutter\ephemeral\.plugin_symlinks\desktop_webview_auth\windows\desktop_webview_auth_plugin.cpp(20,10): fatal error C1083:  
  Cannot open include file: 'atlstr.h': No such file or directory [D:\Source\myuiproject\ui\build\windows\plugins\desktop_webview_auth\desktop_webview_auth_plugin.vcxproj] 
  [        ]     0 Warning(s)
  [        ]     1 Error(s)
  [        ] Time Elapsed 00:00:06.55
  [  +18 ms] Building Windows application... (completed in 7.0s)
  [   +1 ms] "flutter windows" took 7,485ms.
  [   +3 ms] Build process failed.
  [        ]
             #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
             #1      _runBuild (package:flutter_tools/src/windows/build_windows.dart:314:5)
             <asynchronous suspension>
             #2      buildWindows (package:flutter_tools/src/windows/build_windows.dart:80:5)
             <asynchronous suspension>
             #3      BuildWindowsCommand.runCommand (package:flutter_tools/src/commands/build_windows.dart:55:5)
             <asynchronous suspension>
             #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
             <asynchronous suspension>
             #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
             <asynchronous suspension>
             #6      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
             <asynchronous suspension>
             #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
             <asynchronous suspension>
             #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
             <asynchronous suspension>
             #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
             <asynchronous suspension>
             #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
             <asynchronous suspension>
             #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
             <asynchronous suspension>
             #12     main (package:flutter_tools/executable.dart:94:3)
             <asynchronous suspension>
  
  
  [ +105 ms] ensureAnalyticsSent: 102ms
  [   +1 ms] Running shutdown hooks
  [        ] Shutdown hooks complete
  [        ] exiting with code 1
  ```
</details>

<details>

<summary>I have the most up to date windows build tools 2019 and using visual studio 2022. </summary>

![image](https://user-images.githubusercontent.com/1707575/168718718-e9ccb137-feaa-456f-be8d-7eb97507f1d1.png)

</details>

I am a little stumped as to why this build is failing? Any ideas would be greatly appreciated :)

**Comment by coman3** [comment]
Alright, after some time i realized that this build is only failing on windows environments with the NodeJS C++ build tools installed first. I was missing the C++ option within visual studio but had the build tools already installed from node (making me assumed i checked the C++ option previously). 

This was an easy fix by just uninstalling the build tools, and modifying visual studio with the required C++ build option 😅

**Comment by pr-Mais** [comment]
Thanks for sharing your experience 🙌🏻

**Comment by sonjinho** [comment]
Thank you so much
